### ISSUE TITLE
能不能增加功能：将所选条目语言字段设置为zh

### ISSUE THREAD

**Issue by ayue2019** [redleafnew/delitemwithatt#1]
您好，请问可以增加一个类似的功能吗？
将所选条目语言字段设置为zh

**Comment by redleafnew** [comment]
为什么有这个需要？放在哪呢。都放右键太乱了。

**Comment by ayue2019** [comment]
为了解决中英文混排问题，一开始只有变成 zh 才能正确显示 “等”，不过这个问题已解决，感谢作者回复。

**Comment by redleafnew** [comment]
设置为en就是为解决中英文混排的。
一些为中英文混排而编辑的样式及Zotero技巧见https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl

**Comment by aflyingnoob** [comment]
救命，这个功能真的救我狗命了 zotero6好像默认不会自己变 一堆英文中夹着等

**Comment by redleafnew** [comment]
如果有问题，请新开issue。



> 救命，这个功能真的救我狗命了 zotero6好像默认不会自己变 一堆英文中夹着等
