### ISSUE TITLE
增加快捷键设置

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/delitemwithatt#10]
能否为这四个功能增加快捷键
删除附件和条目（delete i(tem)），仅删除所有附件delete a(ttahcment)，仅删除快照delete s(napshot)，仅删除笔记delete n(otes)
感恩！

**Comment by redleafnew** [comment]
用Delete作为快捷键不太顺手。要先按字母，再按Delete。

**Comment by fredericky123** [comment]
> 用Delete作为快捷键不太顺手。要先按字母，再按Delete。
用D?
我暂时没想到更好的快捷键组合方式

**Comment by redleafnew** [comment]
alt + ？

**Comment by fredericky123** [comment]
> alt + ？

长按alt键会提示item在哪个文件夹，我刚才试按alt a 会导致触发上述操作哎

**Comment by fredericky123** [comment]
其实我觉得用delete +还好 习惯了就一瞬间找到delete键了

**Comment by redleafnew** [comment]
默认一按Delete就是删除条目了吧。

**Comment by fredericky123** [comment]
> 默认一按Delete就是删除条目了吧。

会跳出弹窗，估计只能先按字母键了
要是按alt，会导致删附件等的同时，文件夹那里闪动了一下，这样看来还是用d?

**Comment by redleafnew** [comment]
你先Fork一下，设置一下吧，很简单，参考影响因子那个插件。

**Comment by fredericky123** [comment]
> 你先Fork一下，设置一下吧，很简单，参考影响因子那个插件。

好的！

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs/blob/495640eb57caa7c6efbe4694d31e4777ec78a17e/chrome/content/overlay.xul#L13-L19

**Comment by fredericky123** [comment]
> https://github.com/redleafnew/zotero-updateifs/blob/495640eb57caa7c6efbe4694d31e4777ec78a17e/chrome/content/overlay.xul#L13-L19

一目了然，感谢老师！

**Comment by fredericky123** [comment]
有没有计划推动一下快捷键，感谢呀

**Comment by redleafnew** [comment]
我以为你自己已经修改好了。

用ctrl或alt+？？

现在ctrl+D，ctrl+P已经被占用了。

**Comment by fredericky123** [comment]
> 我以为你自己已经修改好了。
> 
> 用ctrl或alt+？？
> 
> 现在ctrl+D，ctrl+P已经被占用了。

主要是一更新，又得重新设置了，希望整合进方案

用某字母+delete?
i(tem)+delete
(a)ttachment+delete
(n)ote+delete
s(nap)+delete
?

**Comment by redleafnew** [comment]
你自己试过吗？这种方法可以设置快捷键吗？

**Comment by fredericky123** [comment]
还没有唉

**Comment by fredericky123** [comment]
如果不行的话，就用字母d代表delete，这样 note+d等肯定都能用

**Comment by redleafnew** [comment]
可以不用修饰键，只有一个字母，如按I就会删除条目附件，但容易误碰，即按I就会提示删除条目和附件。
或是与ctr，shift， alt结合。
但无法与Delete键结合。

**Comment by fredericky123** [comment]
那就用ctrl键也好
会与其他已有的重复么

**Comment by redleafnew** [comment]
现在ctrl+D，ctrl+P已经被占用了。

**Comment by fredericky123** [comment]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/13982749/172001279-a77e8a88-8c35-43ae-adbf-132f15471c19.png">
应该用不到以上这俩
分别对应 ctrl i/a/s/n/e/z (zhaiyao)?

**Comment by redleafnew** [comment]
<img width="149" alt="20220604214613" src="https://user-images.githubusercontent.com/22135631/172003507-8319d2fc-cc4f-417b-96c4-990b6ed50876.png">
ctrl占用得还是比较多的。
用alt吧

**Comment by fredericky123** [comment]
要不用shift?
按住alt会定位item所在文件夹

**Comment by redleafnew** [comment]
CTRL是定位文件的，不是alt，Shift是默认大写啊。

**Comment by fredericky123** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/13982749/172003785-3c17b7bb-ba45-454b-9563-9239bc4ba569.png">
好吧 mac和linuxlinux是alt/option

**Comment by fredericky123** [comment]
win的alt对应mac的option，不知道设置好在mac下每次删除会不会总是先高亮文件夹位置

**Comment by redleafnew** [comment]
会高亮，但快捷键也可以用。

**Comment by fredericky123** [comment]
可以先试试，如果有问题就用ctrl alt +字母，对应mac的command+option+字母

**Comment by redleafnew** [comment]
已更新。

**Comment by fredericky123** [comment]
感谢，发表alt a与最好用的Bob词典的快捷键冲突了
https://github.com/ripperhe/Bob

建议老师用ctrl+alt哎
感谢老师！！

**Comment by redleafnew** [comment]
再试一下？

**Comment by fredericky123** [comment]
完美了！
感谢！
