### ISSUE TITLE
有关插件功能的咨询

### ISSUE THREAD

**Issue by fyqqyf** [redleafnew/delitemwithatt#11]
想请问一下，在没有安装该附件的情况下直接删除条目的话，附件是不会被删除吗？

**Comment by redleafnew** [comment]
主要是针对安装了ZotFile插件以后，删除条目时不会同时删除附件，会形成很多“孤儿”文件。

**Comment by redleafnew** [comment]
你可以打开附件目录看看有些已经删除了条目的附件是否还在，或是在附件链接上右击，然后打开文件位置，再在Zotero中删除条目，看看附件是否也被删除了。

**Comment by redleafnew** [comment]
那估计你没有用ZotFile的重命名和转移位置功能，
你的附件位置是在storage中，且Zotero中附件的pdf图标中没有那个小链子？

**Comment by redleafnew** [comment]
如果没有用ZotFile的重命名且转移附件功能，在删除条目清空Zotero回收站时会删除附件，这个插件主要针对使用了这个功能的。
