### ISSUE TITLE
最近版本插件功能咨询

### ISSUE THREAD

**Issue by DangeRS2** [redleafnew/delitemwithatt#12]
作者你好，

想问个问题，为什么我选择`删除附件和条目`，该条目还是会出现在回收站？并且，当我在回收站再次执行`删除附件和条目`，该条目还是在回收站。

**Comment by redleafnew** [comment]
出现在回收站是正常的，在回收里需要执行清空回收站。
如果还在的话，重新启动一下Zotero。

**Comment by DangeRS2** [comment]
懂了懂了，感谢~
