### ISSUE TITLE
Files remain on the harddrive

### ISSUE THREAD

**Issue by adeldaoud** [redleafnew/delitemwithatt#13]
Hi! I tried delitemwithatt, and it removes the attachment in Zotero but the files remain on the harddrive. That defeats the purpose of this plugin. Is this a bug perhaps?

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/201839638-0ca5b4e5-7935-4a6a-a7f0-cad31b45630e.png)
Do you use the context menu in this plugin?

**Comment by adeldaoud** [comment]
Yes, I deleted the html folder attachment from there, but the folder remains. Is there a difference between file and a folder attachment perhaps?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by redleafnew** [comment]
The folder deletion has been considered, and did not added in the plugin in case of there were more than one files in the folder.

**Comment by redleafnew** [comment]
And you can scan and delete the empty folder with other application if there is only one file in the folder.

**Comment by adeldaoud** [comment]
I see. It would be very useful to delete folders as well, as HTML items will be saved in a folder with multiple files. Those multiple fiels are the ones that are hardest to get rid off manually. Would it be possible to add that feature of deleting a folder? It would be  very very useful.

**Comment by redleafnew** [comment]
It will not happen in the near future, sorry. For the HTML items, they could be saved as single web page file with mhtml as the extenstion.
![image](https://user-images.githubusercontent.com/22135631/201856045-b2ff1125-4dbd-47d7-82d9-29087abc7fbf.png)

**Comment by adeldaoud** [comment]
Good idea reagrding the mhtml. Sorry to hear that it will not be supported any time soon. Incidentally, do you have a suggestion for how I can get rid of those specific folders from Zotero and my harddrive in a batch operation?

 Zotero creates those folders for HTML attachments from the past, containing multiple files. I really would like to batch delete all items with HTML folders. I am setting up a sync folder solution on Onedrirve, according to Zotero instructions of splitting the database and attached files. However, having a myriad of tiny files is creating issues for OneDrive

**Comment by redleafnew** [comment]
After searching, the script was found, however, I did not try it.

https://devblogs.microsoft.com/oldnewthing/20080417-00/?p=22703

**Comment by adeldaoud** [comment]
Thanks for the tip. However, the Zotero storage folders I am referring to are not empty. They live in the Zotero storage folder like so, and wondering if those can be deleted, for the ones with HMTL files.
![image](https://user-images.githubusercontent.com/9431362/201862647-7da7951e-76de-4ab1-9bed-3cb018800d3e.png)

**Comment by redleafnew** [comment]
You could use ZotFile, move the attachments to another folder, then the attachnents with items will be moved the folder, and the orphan attachments will not.
