### ISSUE TITLE
delete bug

### ISSUE THREAD

**Issue by Summittk** [redleafnew/delitemwithatt#14]
Folders still exist in the right-click Add category.

**Comment by redleafnew** [comment]
Folders deletion is not supported.

**Comment by Summittk** [comment]
I used your plugin to select Delete all attachments and items in the Delete folder operation, but the folder still exists in the zotero right-click menu

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/202601115-dc2435ae-8ac8-4c9f-9852-153a26a472ed.png)
Do you mean the collection still exist aftert this operation here?

**Comment by Summittk** [comment]
I have these folders in my library![image](https://user-images.githubusercontent.com/109151399/202601773-5ccb4193-5670-4d70-847f-38b5c5b4f499.png)
but in the option of Add the category, The previously deleted folder still exists.
![image](https://user-images.githubusercontent.com/109151399/202601899-cd342840-a504-41c5-aae6-eed65a5c36de.png)

**Comment by Summittk** [comment]
Can you help me solve this bug, which affects the experience and collaboration with zotero connect plugin. Thank you very much.

**Comment by redleafnew** [comment]
了解了，我看看。

**Comment by redleafnew** [comment]
找到可以删除文件夹的函数了，但以前还不知道怎么清除。
https://groups.google.com/g/zotero-dev/c/vELyCA2oMeY

**Comment by Summittk** [comment]
能帮忙找一下找到分类文件夹存放位置，我感觉就能删干净。

**Comment by redleafnew** [comment]
**直接修改数据库文件，非常危险，一定要备份数据目录。**
1. 备份数据目录
![image](https://user-images.githubusercontent.com/22135631/202653298-6597fe89-a35b-442f-a58d-49fe7d36a346.png)

2. 从https://github.com/sqlitebrowser/sqlitebrowser/releases下载DB Browser for SQLite，运行DB Browser for SQLite

3. 用DB Browser for SQLite打开自己数据目录内的zotero.sqlite文件

![image](https://user-images.githubusercontent.com/22135631/202653622-03e27b51-4ff5-4016-a541-25a35b3fdaf1.png)
![image](https://user-images.githubusercontent.com/22135631/202653759-8a7a3cf9-8f15-4939-8824-c45591d0795a.png)

4. 点击浏览数据--表后面的collections--选中下面的记录--右击--删除记录
7. 
![image](https://user-images.githubusercontent.com/22135631/202654263-58ac74c9-4582-42d2-a9c3-5ba90cc69cb5.png)

**Comment by Summittk** [comment]
大佬牛逼，成功解决，十分感谢！希望你也能修复一下这个bug，感恩！

**Comment by redleafnew** [comment]
升级了，试试看。
https://github.com/redleafnew/delitemwithatt/releases/tag/0.0.20

**Comment by Summittk** [comment]
可以的，没问题了
