### ISSUE TITLE
Shortcuts are not working

### ISSUE THREAD

**Issue by Dellu** [redleafnew/delitemwithatt#18]
`Delete Attachment(s) and Item(s)(Alt+I), Delete All Attachment(s) only(Alt+A), Delete Snapshot(s) only(Alt+S), Delete Note(s) only(Alt+N), Empty Abstract(s)(Alt+Z), Empty Extra(s)(Alt+X)`

Are those in brackets supposed to be keyboard shortcuts?
If that is the intention, they are not working for me (on the mac). 

Can you add more universal type of shortcuts please?

**Comment by redleafnew** [comment]
Yes， they are supposed to be shortcuts, and I have not a Mac, therefore they can not be tested. 

And https://www.makeuseof.com/alt-key-on-mac/ says Alt on Mac is another key.

> Can you add more universal type of shortcuts please?

Which keys do you expect?

**Comment by redleafnew** [comment]
@Dellu 
Does it work？
