### ISSUE TITLE
语言设置bug

### ISSUE THREAD

**Issue by pencilheart** [redleafnew/delitemwithatt#19]
您好，当批量进行中英文语言填充时，遇到`item type`为`software`会停止此操作，且无弹窗说明。可否设置跳过此类item？

**Comment by redleafnew** [comment]
如果仅一条software有什么提示？方便提供一下条目吗？

**Comment by redleafnew** [comment]
应该是这个文献类型没有语言这个字段。我修改一下。

**Comment by pencilheart** [comment]
> 应该是这个文献类型没有语言这个字段。我修改一下。

是的，没有语言字段。感谢！

**Comment by redleafnew** [comment]
你想跳过后有错误提示吗？

**Comment by redleafnew** [comment]
请更新，现在是只有一条且文献类型为软件，如果更新会有语言设置失败提醒，如果多条中包含软件，则不会提示失败。

**Comment by pencilheart** [comment]
非常棒！问题已完美解决～

**Comment by redleafnew** [comment]
还是有些问题，如果选中的全部都是软件，还是会提示成功。

**Comment by pencilheart** [comment]
提示成功应该是对的，因为已经把可以设置的语言全都设置成功了。或者可以设置提示条件：在包含软件条目时，成功提示为“xx个条目无语言项，其余更新完成”？

**Comment by redleafnew** [comment]
更新了，现在如果全是软件是会提示更新错误，如果包含软件，但有其它条目提示成功。
