### ISSUE TITLE
无法删除attachment中的note

### ISSUE THREAD

**Issue by ChunwuZhu** [redleafnew/delitemwithatt#2]
您好，目前插件无法删除attachment里面的note，不知道您能否设置一个选项来设置删除哪些后缀名的附件或者哪些类型的附件，谢谢！

**Comment by redleafnew** [comment]
只删除里面的Note？

**Comment by ChunwuZhu** [comment]
> 只删除里面的Note？

现在是无法删除attachment里面的note，如果attachment里面只有note的话，选项是灰色的，无法选择。所以看您能否设置在选项里添加一个删除note？

不过我找到了其他方法来批量删除note，采用高级检索的方式来也行。

**Comment by redleafnew** [comment]
我没有遇到过批量删除笔记的情况，所以当时没有考虑。什么情况需要批量删除笔记。

**Comment by ChunwuZhu** [comment]
> 我没有遇到过批量删除笔记的情况，所以当时没有考虑。什么情况需要批量删除笔记。

参考文献从数据库里自动导出的时候偶尔会遇到自动生成的多余note。好像是在scopus里导出ris文件，再导入zetoro的时候会产生两个多余的note，用于记录导出时间和被引数量，所以需要把这两个多余的note批量删除掉。

**Comment by redleafnew** [comment]
发几条导入的ris文件给我吧，redleafnew@163.com，我有时间了试试。

**Comment by ChunwuZhu** [comment]
> 发几条导入的ris文件给我吧，[redleafnew@163.com](mailto:redleafnew@163.com)，我有时间了试试。
好的

**Comment by redleafnew** [comment]
已添加，请测试。

**Comment by ChunwuZhu** [comment]
好的，感谢！
