### ISSUE TITLE
本插件和style插件冲突

### ISSUE THREAD

**Issue by Serendipity-LJ** [redleafnew/delitemwithatt#21]
如题

**Comment by redleafnew** [comment]
如何冲突，有什么表现？

**Comment by Serendipity-LJ** [comment]
1.都安装最新版本插件后，打开zotero时文库文件夹右边里的条目和附件一片空白，啥也没有
2.style插件正常的话，标签默认在中间显示、右击标题栏菜单比较全，但是更新了0.0.20以后版本的本插件后签署正常状态被破坏，禁用或者回退则恢复正常
以上，应该是不兼容吧 辛苦大佬~

**Comment by Serendipity-LJ** [comment]
> 

见评论区

**Comment by Serendipity-LJ** [comment]
> 只安装或禁用其中一个正常?

我不记得有没有使用最新版本插件和禁用style插件了（因为style用习惯了，可能没有打算禁用）。但是安装最新版style后，再把本插件回退到0.0.20版本就正常了，没有前述评论的问题了，试了试本插件近三周的更新版本都不行，只能回退0.0.20版本。

**Comment by redleafnew** [comment]
以前的没有用框架，在Zotero 7.0时会不能用。

**Comment by Serendipity-LJ** [comment]
好吧 也给style作者反映了，应该可以都兼容使用最好了 打扰了，感谢

**Comment by redleafnew** [comment]
> > 只安装或禁用其中一个正常?
> 
> 我不记得有没有使用最新版本插件和禁用style插件了（因为style用习惯了，可能没有打算禁用）。但是安装最新版style后，再把本插件回退到0.0.20版本就正常了，没有前述评论的问题了，试了试本插件近三周的更新版本都不行，只能回退0.0.20版本。

可以试试禁用一下，是否正常了。

**Comment by redleafnew** [comment]
重新用用新工具箱编译了一下，看一下现在正常了吗？

**Comment by Serendipity-LJ** [comment]
> 重新用用新工具箱编译了一下，看一下现在正常了吗？

正常了哎！！！！谢谢大佬
最新版本插件和style插件可以共存了~

**Comment by redleafnew** [comment]
好的，
