### ISSUE TITLE
删除条目时同时删除PDF

### ISSUE THREAD

**Issue by zzzyzh** [redleafnew/delitemwithatt#22]
作者您好，我想请问一下这款插件可以在删除条目的时候同时删除对应的pdf文件吗？

**Comment by zzzyzh** [comment]
> 这个插件就是干这个的

可是我发现我用zotfile移动和改名后，使用删除条目这个选项并不能删除对应的pdf，请问是有什么需要设置的地方吗（Mac电脑）

**Comment by redleafnew** [comment]
要用插件提供的右键菜单。
![image](https://user-images.githubusercontent.com/22135631/224325079-8f9669b0-bfdf-41c4-9808-00a446d7e1d6.png)
