### ISSUE TITLE
插件不工作问题

### ISSUE THREAD

**Issue by Muskteer98** [redleafnew/delitemwithatt#25]
**文章 和 附件 都在**
![image-20230804131703126](https://github.com/redleafnew/delitemwithatt/assets/29146415/02aec7cf-0c4e-44a3-9aa9-d6de8c579174)

### **选择删除条目和附件后，虽然有对话框跳出，但实际并未删除，条目依旧存在。选择 删除条目才可以删除到回收站。**
![image-20230804132126940](https://github.com/redleafnew/delitemwithatt/assets/29146415/de40a192-23f4-4542-8ec1-9c66806f54f2)

![image](https://github.com/redleafnew/delitemwithatt/assets/29146415/d5763082-39da-46e5-bd0a-49db76ce0627)

**Comment by redleafnew** [comment]
Zotero 7.0的吗？
是所有都不行，还是偶尔有不行的。

**Comment by redleafnew** [comment]
应该是7.0升级后带来的问题。

**Comment by jlu511** [comment]
像楼主这种链接的附件，用这个插件删除，无效果，目标文件夹下，链接的pdf还在。

**Comment by Muskteer98** [comment]
> Zotero 7.0的吗？ 是所有都不行，还是偶尔有不行的。

**zotero 版本为 7.0.0-beta.27。 在之前zotero6 上是可以正常使用的。**
插件版本  0.2.0。

目前安装插件如下
![image](https://github.com/redleafnew/delitemwithatt/assets/29146415/83e40d38-6da3-4083-95f2-2a2c2e402127)

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=a97f0337-afaa-4539-d871-08db94dc6a8e&fromMyShare=True

Zotero升级后不支持 OS.File操作了，需要修改代码。可以先用这个quicker动作，附件和条目都进回收站，而不是直接删除了。

**Comment by Muskteer98** [comment]
> 

### 好的，谢谢您。十分期待您的下一次更新
研究了一下这个方法。想使用的朋友可以看下，大概是以下安装步骤
**1.下载安装quicker  https://getquicker.net/Download**
![image](https://github.com/redleafnew/delitemwithatt/assets/29146415/5070bca4-4e23-4526-8489-739e555cd0d0)

**2.安装debug-bridge 插件 以及运行代码  ，可参考这个网页 https://www.yuque.com/chentaotao-cf9fr/gthfy4/clqahv57w5ugmdev**
![image](https://github.com/redleafnew/delitemwithatt/assets/29146415/d544d565-da8b-4a8e-8578-d8268e6d1047)

### 3. 安装动作，作者在上面提供的网址里的动作，如何安装可以点击网页上的“如何安装动作查看”，安装好后可以设置快捷键操作。这样便可以删除附件和条目了。
![image](https://github.com/redleafnew/delitemwithatt/assets/29146415/b4d48340-951f-43c4-8a42-faf9baf1d39b)

**Comment by redleafnew** [comment]
quiker很强大，下面有不少Zotero的动作。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/delitemwithatt/releases/tag/0.2.1

**Comment by redleafnew** [comment]
https://github.com/redleafnew/delitemwithatt/releases/tag/0.2.2
