### ISSUE TITLE
mac下快捷键失效

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/delitemwithatt#26]
记得以前是ctrl alt +字母，对应mac的command+option+字母
https://github.com/redleafnew/delitemwithatt/issues/10
option对应的是alt
现在用alt加字母也不行了

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/issues/73
麻烦你在Mac上按上面链接试试，alt显示的是什么吧。前面你测试过ctrl对应的是meta。

**Comment by fredericky123** [comment]
现在zotero 7下 zutilio失效了 没法自定义一个option的快捷键来测试了
不知道有没有其他测试技巧
或者只能能zutilio能用了再测试

**Comment by redleafnew** [comment]
其它的技巧我也不知道了。或是临时下载个Zotero 6的试试。或是等Zotero 7的zutilo出来再说。

**Comment by fredericky123** [comment]
zotero7最新试用版数据结构改变已经回不去了，等zutilo 7出来后我再更新吧

**Comment by redleafnew** [comment]
下载Zotero 6,搞个新的配置，启动时 运行 加-p参数
