### ISSUE TITLE
求一个简化版本

### ISSUE THREAD

**Issue by FunnyLinSir** [redleafnew/delitemwithatt#27]
大佬，请问可以精简一下，只保留“删除条目和附件”功能吗，直接提到右键的一级目录，其他的都砍掉

**Comment by redleafnew** [comment]
现在按快捷键Alt+I也可以删除条目和附件。导出附件，

**Comment by redleafnew** [comment]
导出附件，自动设置语言也不需要。
你用不用quicker？可以写一个动作。

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=a97f0337-afaa-4539-d871-08db94dc6a8e

**Comment by FunnyLinSir** [comment]
> 现在按快捷键Alt+I也可以删除条目和附件。

芜湖，学到了，谢谢大佬！
