### ISSUE TITLE
本插件导致zotero条目显示空白

### ISSUE THREAD

**Issue by lllaterOn** [redleafnew/delitemwithatt#28]
使用本插件的时候，有时候打开zotero条目会显示空白，这时候只能删掉插件，重新安装才有可能恢复正常。请问可以麻烦大佬修复一下吗？Zotero版本为6.0.27，插件版本为0.1.06
![b2e52eb87e0e1fa5c28998ed50a3170f](https://github.com/redleafnew/delitemwithatt/assets/78646625/7c12e5b4-8ce7-4005-8ee6-5a8dd34bb5d8)

**Comment by redleafnew** [comment]
没有见过这个问题
