### ISSUE TITLE
可以在添加每一个条目的时候自动设置 language 域吗？

### ISSUE THREAD

**Issue by panmengguan** [redleafnew/delitemwithatt#31]
也就是对于新添加的条目，不需要再次点击一遍？

**Comment by redleafnew** [comment]
不再进行复杂设置了。可以多选右击设置语言。

**Comment by panmengguan** [comment]
好吧，不太明白为什么 Zotero 7 会将所有从浏览器 zotero connector 保存的条目语言都设置成 zh-CN

**Comment by redleafnew** [comment]
估计是转换器translator的问题

**Comment by panmengguan** [comment]
> 估计是转换器translator的问题

应该是的，谢谢，我再看看
