### ISSUE TITLE
无法导出PDF文件

### ISSUE THREAD

**Issue by Chuyu-Guo** [redleafnew/delitemwithatt#32]
你好！
我刚刚下载了适合Zotero 6.0的delitemwithatt，安装好了。
随便选择一个条目（带有附件），右键单击，选择“导出附件”，会弹出一个窗口问需要把文件储存在哪个地方，选择好后，会同时出现两条信息（见下图），一条说导出成功，一条说导出失败。并且在选择的地址，找不到导出文献的PDF文件。
请问是哪里出了问题呀？
我的电脑是Mac, Zotero版本6.0.35

<img width="308" alt="图片 1" src="https://github.com/redleafnew/delitemwithatt/assets/130462096/99f905c4-8e68-4987-9f83-be87c564a646">

**Comment by redleafnew** [comment]
Mac的没有试过，6.0的没有精力维护了。
