### ISSUE TITLE
如何修改删除附件的快捷键（Alt+A和微信截图冲突了）

### ISSUE THREAD

**Issue by ramonmi** [redleafnew/delitemwithatt#33]
如题，虽然可以修改微信的快捷键，但是如果可以增加插件快捷键的自定义就更好了

**Comment by redleafnew** [comment]
https://github.com/redleafnew/delitemwithatt/releases/tag/0.3.0

**Comment by ramonmi** [comment]
感谢，那我将此issue关闭了
