### ISSUE TITLE
不兼容6.0.36

### ISSUE THREAD

**Issue by etherbard** [redleafnew/delitemwithatt#35]
6.0.36从文件安装失败
![image](https://github.com/redleafnew/delitemwithatt/assets/36912362/13bdb587-d2d9-4277-a4a2-9b2db98dd046)

**Comment by redleafnew** [comment]
https://github.com/redleafnew/delitemwithatt?tab=readme-ov-file#%E6%B3%A8%E6%84%8F

**Comment by nicolnt** [comment]
Get latest version for Zotero 6 here: https://github.com/redleafnew/delitemwithatt/releases/tag/0.1.06
