### ISSUE TITLE
该插件右下角通知能否关闭？

### ISSUE THREAD

**Issue by shaojunjie0912** [redleafnew/delitemwithatt#36]
如下图，通知一直置顶，切换到别的页面还是会继续显示，只能手动关闭。

![image](https://github.com/redleafnew/delitemwithatt/assets/96936298/ecf7a048-daf4-4865-a209-51a443f3201d)

**Comment by YIRU69** [comment]
请问，这个问题你解决了吗？

**Comment by shaojunjie0912** [comment]
只是偶尔会出现这种情况，大部分情况下还是会自己关闭的，可能只有当从zotero切换到别的页面时偶尔会无法自动关闭

**Comment by shaojunjie0912** [comment]
> 请问，这个问题你解决了吗？

只是偶尔会出现这种情况，大部分情况下还是会自己关闭的，可能只有当从zotero切换到别的页面时偶尔会无法自动关闭
