### ISSUE TITLE
Small adjustment on the usage note

### ISSUE THREAD

**Issue by nhan000** [redleafnew/delitemwithatt#6]
Per version 0.0.12 attachments now move to recycle bin and not deleted permanently. 

Maybe change the last sentence in the Usage Note accordingly? "Note: the linked files could not be restored, they will be removed directly, please backup before removing."

**Comment by redleafnew** [comment]
Thanks.

The linked files which renamed and moved by `ZotFile` could not be restored still, though they are in the `Trash` of `Zotero`, after they are restored, when you open the attachment, <code>Zotero</code> will prompt `The attached file could be found at the following path:...`.

The `Stored files` which managed by` Zotero` could be restored.

**Comment by redleafnew** [comment]
If the function <code>Convert Linked Files to Stored Files</code> is found, then this plugin could be updated, the the linked files could be restored after they are deleted.

**Comment by nhan000** [comment]
Understood. Thanks so much for writing this add-ons.
