### ISSUE TITLE
如何删除zotero/storage下的重复文件夹

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/delitemwithatt#8]
看了很过关于如何删除zotfile下遗留文件的教程，我第一次使用zotfile重命名并移动文件后，发现zotero/storage下遗留了很多乱码文件夹，这些文件夹里的pdf在zotfile文件夹内都有对应的，我的猜测是之前有重复附件，被移过去了还有剩余，怎么删除zotero/storage下的重复文件夹？

我手动直接删了，然后重置同步历史，用本地的取代网上的，还是会把网上的附件下载到zotero/storage下，奇怪了

**Comment by redleafnew** [comment]
印象中有clean 或 scan storage的插件。
可以指定新的附件文件夹，利用ZotFile再转移一次。
storage中的有可能是用了Zotero自带的同步功能的附件。

**Comment by fredericky123** [comment]
> 印象中有clean 或 scan storage的插件。 可以指定新的附件文件夹，利用ZotFile再转移一次。 storage中的有可能是用了Zotero自带的同步功能的附件。

插件名字应该叫storage scanner
我也觉得storage中的是zotero自带同步的附件，却怎么都删除不了网上已同步的内容了
zotfile再转移会删除zotfile下的遗留pdf，但是对原storage下的好像没有影响
我再根据这个教程试试
https://www.zotero.org/support/kb/sync_reset_options

**Comment by fredericky123** [comment]
尴尬了，尝试删了那么久，各种删不掉，忽然看到zotero/storage下储存的乱码文件应该是group文件夹里的资料
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13982749/156907419-7fcf71d5-e778-4f40-862e-d8ca2da9d4ec.png">
难怪各种同步都删不掉啊

**Comment by redleafnew** [comment]
group的附件不支持用其它同步。

**Comment by fredericky123** [comment]
> group的附件不支持用其它同步。

是的，我以为那些乱码是my library的，结果发现是group的，各种删除，花了半天时间，吃一堑长一智
