### ISSUE TITLE
storage下的空白文件夹如何删除

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/delitemwithatt#9]
发现导入题录时，zotfile的移动重命名的操作过程是先将pdf下载到storage下，然后再移走重命名，因此在storage下留下了很多空白的乱码文件夹，这些个文件夹如何删除呢
storage scaner 只能删除重复或broken的附件，不能删除空白文件夹

**Comment by redleafnew** [comment]
确定是空白的文件夹？里面好像还有大概两个小文件。

**Comment by fredericky123** [comment]
> 确定是空白的文件夹？里面好像还有大概两个小文件。

我确实是空白的
![image](https://user-images.githubusercontent.com/13982749/157606621-0cfa5b20-d146-4cb7-80d7-d0792cb748bf.png)
![image](https://user-images.githubusercontent.com/13982749/157606643-c492c07b-9dea-427d-a862-ce7c2ab5ded8.png)

**Comment by redleafnew** [comment]
.zotero-ft-cache 我的文件夹中有的还有这个文件

**Comment by redleafnew** [comment]
以前想写过一个规则，如果文件夹大小小于某个尺寸就删除，但是论坛上问时，这些小文件是有用的，就没有搞。

**Comment by fredericky123** [comment]
> .zotero-ft-cache 我的文件夹中有的还有这个文件



> 以前想写过一个规则，如果文件夹大小小于某个尺寸就删除，但是论坛上问时，这些小文件是有用的，就没有搞。

我从没见过这个文件唉
不知道那一堆空白的文件有啥用，delitemwithatt如果能扫描是不是空白文件夹，并删除就好了

**Comment by fredericky123** [comment]
> zotero-ft-cache

或许可以删掉试试影不影响附件的打开

**Comment by redleafnew** [comment]
https://forums.zotero.org/discussion/88778/how-to-clean-up-8-digits-random-strings-folder-in-storage-folder#latest
小文件是全文索引的。以前问过。

**Comment by redleafnew** [comment]
https://forums.zotero.org/discussion/88778/how-to-clean-up-8-digits-random-strings-folder-in-storage-folder#latest
小文件是全文索引的。以前问过。

**Comment by fredericky123** [comment]
https://forums.zotero.org/discussion/21422/pdf-is-stored-but-zotero-ft-cache-and-zotero-ft-info-are-not-created
我也找到了
然后我发现我的文件夹里也有！
文件被隐藏了
那就不能删除了

**Comment by redleafnew** [comment]
对，官方建议最好是不动它们。

**Comment by fredericky123** [comment]
> 对，官方建议最好是不动它们。

感谢！
